
(gnat -> {}) print_gnat <is> <output>;
(gnat -> gnat) echo <is> (... -> $ | print_gnat | $);
(gnat -> gnat) es <is> echo | succ;

gnat trace <is> 0  | es | es | es | es | es | es | es | es  | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es| es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es| es | es | es | es | es | es | es | es  | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es| es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es| es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es| es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es | es;


gnat main <is> {'x 2, 'y 5} | x+y;

